### ISSUE TITLE
problem in converting numbers

### ISSUE THREAD

**Issue by profnami** [shuchkin/simplexlsx#76]
hi author, 
thank you so much for your useful lib,
but i have a problem when i convert numbers in XLSX file for exmple:
i have this number : -1.35 and it converts to -1, also i have 1.1, 2.23 and ... but all of them converted to round numbers. but i need the real numbers. can i fix this issue?

**Comment by shuchkin** [comment]
give me your xlsx for tests

**Comment by ZXDragon360** [comment]
Hello, same thing for mine. My data file contains one of the columns for a product ID which is around 16 numeric digits. When I tried to export it, the output file shows the number had been shortened to the max digits of only 6 digits plus an exponential symbols to replace my values. Is there any way to preserve the number as is when export from original to output without modifying that value?

**Comment by shuchkin** [comment]
Re: [shuchkin/simplexlsx] problem in converting numbers (#76)



Hello, Aaron.

see Disable Type Detection example
 https://github.com/shuchkin/simplexlsxgen#data-types







Hello, same thing for mine. My data file contains one of the columns for a product ID which is around 16 numeric digits. When I tried to export it, the output file shows the number had been shortened to the max digits of only 6 digits plus an exponential symbols to replace my values. Is there any way to preserve the number as is when export from original to output without modifying that value?
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.





--
Thank You
Sergey
http://www.sibvision.ru/
http://www.smspilot.ru/
https://twitter.com/shuchkin
https://www.facebook.com/shuchkin
