### ISSUE TITLE
Problem with date format receiving

### ISSUE THREAD

**Issue by DMGPage** [shuchkin/simplexlsx#86]
Hello!

I want to use your library in my project, but I encountered with one problem. I want to send to user error about their value in xlsx file, but in case of date, I can't do that. Your lib returns date in different format, than it's original in file. And even with function "rowsEx" I can't receive it's original format. For example in LibreOffice, I see that date is in format "DD/MM/YYYY". When I get result from rowsEx", I get row, where "format" is equal "mm-dd-yy". From what I can tell, it depends from file writer, but in this case I do not know how it is made. I will add example file in [attachment](https://github.com/shuchkin/simplexlsx/files/5062201/import_5f33b54a1feae_2.xlsx).

And I checked php code and found some post, that looks like, is related to this problem: https://stackoverflow.com/a/23213725

**Comment by shuchkin** [comment]
https://issue.life/questions/34900605

**Comment by DMGPage** [comment]
Could you describe better, what you want to say with this? That you can make it detect format better or what? In your link I see, that they too mention format "DD/MM/YYYY" and not "mm-dd-yy", which you are using.

**Comment by shuchkin** [comment]
oops, there russian lang

in your xlsx cells with dates marked as numFmtId="14", so reader (Excel) must use Windows locale settings

<img width="529" alt="Screenshot_175" src="https://user-images.githubusercontent.com/315872/90058685-dff16100-dd03-11ea-87c5-7e5600df8fc8.png">

we don't use locale settings and mm-dd-yy hardcoded in library

so, if rowsEx returns "mm-dd-yy" format is OK for your task

**Comment by DMGPage** [comment]
> so, if rowsEx returns "mm-dd-yy" format is OK for your task

Well no, because it's still unpredictable. From result it's impossible to tell, whether locale settings should be used or no. Is it possible to change "rowsEx" function, to return numFmtId value? Or some kind of property, that would tell, that I have to take in account locale settings. Then I could change date to our country format and not show in format, that user would never see here, when opens that file.

**Comment by jpitoniak** [comment]
I'm running into a similar issue.  I'm attempting to parse a file containing bus schedules.  I working on a tool that our transportation office can use to update their website on their own, so I'm trying to accommodate every permutation of a schedule they've ever send me, since there tends to be a lot of inconsistency.

Some of the schedules have a row that contains the travel time from the previous stop, expressed as "0:02:00" for two minutes, whereas the actual times that the bus stops at that stop are expressed as an AM/PM time (i.e. "2:15 PM").  Simplexlsx returns both of these as a time with no way that I can find to get the original field value.  The location of this line, if it's even there, tends to be in a different place in different schedules, so being able to identify it is important.

I've also written my parser in Go and have it working perfectly using the [tealeg/xlsx](https://github.com/tealeg/xlsx) package.  With that package, once I have a reference to a cell, I can call cell.String() and get the string representation of the value as the user would see it in Excel.  I can then use regular expressions to determine if it's a time or a duration.

I was hoping to create a PHP solution, since my team is mostly PHP-centric and I think I'm the only developer on it who uses Go, but the schedules my PHP version returns are inaccurate because it treats the durations as times.

**Comment by shuchkin** [comment]
> mm-dd-yy
https://stackoverrun.com/ru/q/1112381

numFmtId 0-50 specified in Excel Documentation

I don't have plan to change mm-dd-yy to other string

**Comment by shuchkin** [comment]
> I was hoping to create a PHP solution, since my team is mostly PHP-centric and I think I'm the only developer on it who uses Go, but the schedules my PHP version returns are inaccurate because it treats the durations as times.

Why rowsEx() did not work for u?

**Comment by DMGPage** [comment]
> > mm-dd-yy
> > https://stackoverrun.com/ru/q/1112381
> 
> numFmtId 0-50 specified in Excel Documentation
> 
> I don't have plan to change mm-dd-yy to other string

ahh okay, I will extend SimpleXLSX class and change $CF values. I believe, that would fix my problem. Just don't remove possibility to do that.
