### ISSUE TITLE
Preserving leading zeros

### ISSUE THREAD

**Issue by betweenbrain** [shuchkin/simplexlsx#97]
Hello,

I am using your library to parse an XLXS file which contains zip codes with leading zeros, such as 06791. It seems that the leading zeros are getting dropped, so that the above data would be 6791. Is there way to preserve the leading zeros?

The code I am using is nearly identical https://github.com/shuchkin/simplexlsx#rows-with-header-values-as-keys

Thanks!

**Comment by shuchkin** [comment]
Re: [shuchkin/simplexlsx] Preserving leading zeros (#97)



Hello, Matt.

try
print_r( $xlsx->rows() );

and

print_r( $xlsx->rowsEx() );







Hello,
I am using your library to parse an XLXS file which contains zip codes with leading zeros, such as 06791. It seems that the leading zeros are getting dropped, so that the above data would be 6791. Is there way to preserve the leading zeros?
The code I am using is nearly identical https://github.com/shuchkin/simplexlsx#rows-with-header-values-as-keys
Thanks!
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.





--
Thank You
Sergey
http://www.sibvision.ru/
http://www.smspilot.ru/
https://twitter.com/shuchkin
https://www.facebook.com/shuchkin

**Comment by betweenbrain** [comment]
Hi @shuchkin,

Thanks! Both `$xlsx->rows()` and `$xlsx->rowsEx()` display the zip codes without the leading zeros.

**Comment by shuchkin** [comment]
Re: [shuchkin/simplexlsx] Preserving leading zeros (#97)



Hello, Matt.

there number style applied (unsupported for now)
try fix zip in your code

$zip = sprintf('%05d', $zip);






Hi @shuchkin,
Thanks! Both $xlsx->rows() and $xlsx->rowsEx() display the zip codes without the leading zeros.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.





--
Thank You
Sergey
http://www.sibvision.ru/
http://www.smspilot.ru/
https://twitter.com/shuchkin
https://www.facebook.com/shuchkin

**Comment by betweenbrain** [comment]
Hello Sergey,

Thanks! That'll work for now.

Best,
Matt
